apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-single-account
  namespace: mysql

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-single-role
  namespace: mysql
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - pods
      - deployments
      - services
      - replicasets

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-single-rolebinding
  namespace: mysql
subjects:
  - kind: ServiceAccount
    name: mysql-single-account
    namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-single-role
